### ISSUE TITLE
npm  run dev throws error

### ISSUE THREAD

**Issue by mconnor** [chrisvfritz/vue-2.0-simple-routing-example#8]
I run npm install
now running npm run dev but i get an error
The  npm-debug.log reads:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@4.1.1
3 info using node@v7.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-2.0-simple-routing-example@~predev: vue-2.0-simple-routing-example@
6 silly lifecycle vue-2.0-simple-routing-example@~predev: no script for predev, continuing
7 info lifecycle vue-2.0-simple-routing-example@~dev: vue-2.0-simple-routing-example@
8 verbose lifecycle vue-2.0-simple-routing-example@~dev: unsafe-perm in lifecycle true
9 verbose lifecycle vue-2.0-simple-routing-example@~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/mikeconnor/Documents/git repos/vue-2.0-simple-routing-example/node_modules/.bin:/usr/local/sbin:/usr/local/sbin:/Users/mikeconnor/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/mikeconnor/.rvm/bin
10 verbose lifecycle vue-2.0-simple-routing-example@~dev: CWD: /Users/mikeconnor/Documents/git repos/vue-2.0-simple-routing-example
11 silly lifecycle vue-2.0-simple-routing-example@~dev: Args: [ '-c', 'webpack-dev-server --inline --hot' ]
12 silly lifecycle vue-2.0-simple-routing-example@~dev: Returned: code: 1  signal: null
13 info lifecycle vue-2.0-simple-routing-example@~dev: Failed to exec dev script
14 verbose stack Error: vue-2.0-simple-routing-example@ dev: `webpack-dev-server --inline --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vue-2.0-simple-routing-example@
16 verbose cwd /Users/mikeconnor/Documents/git repos/vue-2.0-simple-routing-example
17 error Darwin 16.3.0
18 error argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v7.4.0
20 error npm  v4.1.1
21 error code ELIFECYCLE
22 error vue-2.0-simple-routing-example@ dev: `webpack-dev-server --inline --hot`
22 error Exit status 1
23 error Failed at the vue-2.0-simple-routing-example@ dev script 'webpack-dev-server --inline --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vue-2.0-simple-routing-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --inline --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vue-2.0-simple-routing-example
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vue-2.0-simple-routing-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
Mikes-MacBook:vue-2.0-simple-routing-example mikeconnor$

**Comment by Akiyamka** [comment]
clone and "npm run dev" crash on start
node v7.4.0
npm 4.0.5

npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-2.0-simple-routing-example@~predev: vue-2.0-simple-routing-example@
6 silly lifecycle vue-2.0-simple-routing-example@~predev: no script for predev, continuing
7 info lifecycle vue-2.0-simple-routing-example@~dev: vue-2.0-simple-routing-example@
8 verbose lifecycle vue-2.0-simple-routing-example@~dev: unsafe-perm in lifecycle true
9 verbose lifecycle vue-2.0-simple-routing-example@~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\OpenServer\domains\vue-2.0-simple-routing-example-pagejs\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\OpenServer\modules\php\PHP-7.0-x64;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;C:\Users\Akiya\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Akiya\AppData\Roaming\npm;C:\Users\Akiya\AppData\Roaming\Composer\vendor\bin
10 verbose lifecycle vue-2.0-simple-routing-example@~dev: CWD: C:\OpenServer\domains\vue-2.0-simple-routing-example-pagejs
11 silly lifecycle vue-2.0-simple-routing-example@~dev: Args: [ '/d /s /c', 'webpack-dev-server --inline --hot' ]
12 silly lifecycle vue-2.0-simple-routing-example@~dev: Returned: code: 1  signal: null
13 info lifecycle vue-2.0-simple-routing-example@~dev: Failed to exec dev script
14 verbose stack Error: vue-2.0-simple-routing-example@ dev: `webpack-dev-server --inline --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vue-2.0-simple-routing-example@
16 verbose cwd C:\OpenServer\domains\vue-2.0-simple-routing-example-pagejs
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v7.4.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error vue-2.0-simple-routing-example@ dev: `webpack-dev-server --inline --hot`
22 error Exit status 1
23 error Failed at the vue-2.0-simple-routing-example@ dev script 'webpack-dev-server --inline --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vue-2.0-simple-routing-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --inline --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vue-2.0-simple-routing-example
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vue-2.0-simple-routing-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ejlocop** [comment]
clone -> npm install -> npm run dev crash
node v6.10.0
npm 3.10.10


npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-2.0-simple-routing-example@~predev: vue-2.0-simple-routing-example@
6 silly lifecycle vue-2.0-simple-routing-example@~predev: no script for predev, continuing
7 info lifecycle vue-2.0-simple-routing-example@~dev: vue-2.0-simple-routing-example@
8 verbose lifecycle vue-2.0-simple-routing-example@~dev: unsafe-perm in lifecycle true
9 verbose lifecycle vue-2.0-simple-routing-example@~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Projects\vue-2.0-simple-routing-example\node_modules\.bin;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\cURL\bin;C:\Python27;D:\hadoop-2.7.1\bin;C:\Java\jdk1.7.0_79\bin;C:\ProgramData\ComposerSetup\bin;C:\Program Files\TortoiseHg\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ADMIN\AppData\Roaming\npm;C:\HashiCorp\Vagrant\bin;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Symantec\VIP Access Client\;C:\OpenSSL-Win64\bin\cnf\openssl.cnf;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Ruby22-x64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\cURL\bin;C:\Users\ADMIN\AppData\Local\Programs\Git\cmd;C:\xampp\php;C:\Program Files\MySQL\MySQL Server 5.7\bin;C:\Python27;C:\Users\ADMIN\AppData\Roaming\Composer\vendor\bin;C:\Users\ADMIN\AppData\Local\atom\bin;C:\xampp\php\PEAR\;C:\Users\ADMIN\AppData\Local\Microsoft\WindowsApps;C:\Users\ADMIN\AppData\Roaming\npm;C:\Users\ADMIN\AppData\Local\Yarn\.bin
10 verbose lifecycle vue-2.0-simple-routing-example@~dev: CWD: D:\Projects\vue-2.0-simple-routing-example
11 silly lifecycle vue-2.0-simple-routing-example@~dev: Args: [ '/d /s /c', 'webpack-dev-server --inline --hot' ]
12 silly lifecycle vue-2.0-simple-routing-example@~dev: Returned: code: 1  signal: null
13 info lifecycle vue-2.0-simple-routing-example@~dev: Failed to exec dev script
14 verbose stack Error: vue-2.0-simple-routing-example@ dev: `webpack-dev-server --inline --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vue-2.0-simple-routing-example@
16 verbose cwd D:\Projects\vue-2.0-simple-routing-example
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error vue-2.0-simple-routing-example@ dev: `webpack-dev-server --inline --hot`
22 error Exit status 1
23 error Failed at the vue-2.0-simple-routing-example@ dev script 'webpack-dev-server --inline --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vue-2.0-simple-routing-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --inline --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vue-2.0-simple-routing-example
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vue-2.0-simple-routing-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by chendayang** [comment]
i think maybe because the 'package.json' is not completion

**Comment by chrisvfritz** [comment]
@chendayang I'm not sure what you mean by `package.json` not being complete. 

Either way though, I wasn't able to replicate the problem but just updated all packages, which may fix the issues. Let me know how it goes!

**Comment by chendayang** [comment]
I try again, and its ok.  no error is thrown, thanks
